### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by vmagalhaes** [TypeCtrl/ngx-codemirror#215]
I'm trying to build my project on production and I have this message:

```
ERROR in ./node_modules/@ctrl/ngx-codemirror/fesm5/ctrl-ngx-codemirror.js
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:242:35)
    at checkNodeForDecorators (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:67:21)
    at visitNodes (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14809:30)
    at Object.forEachChild (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15033:24)
    at checkNodeForDecorators (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14928:21)
    at checkNodeForDecorators (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14985:24)
    at checkNodeForDecorators (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14996:24)
    at checkNodeForDecorators (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/victor/Documents/workspace/commander-web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:14893:21)

```

**Comment by scttcper** [comment]
What versions are in your package.json

**Comment by scttcper** [comment]
With angular 8?

**Comment by vmagalhaes** [comment]
No Angular 6

**Comment by vmagalhaes** [comment]
Oh, I need to use version 1.3.10, sorry.

**Comment by vmagalhaes** [comment]
Oh... I need to use 1.3.10.

**Comment by fk1blow** [comment]
Using 2.2.0, it breaks with the same error! 
Works as expected after going back to 2.1.1(angular 8)

**Comment by scttcper** [comment]
tried with a new project using angular 8 compiles fine

**Comment by coloz** [comment]
> tried with a new project using angular 8 compiles fine

@scttcper @fk1blow same error,tried with a new project using angular 8,the error still exists.
Works as expected after going back to 2.1.1(angular 8),too
